### PR TITLE
 Cleanup tokio support and update it for tokio 1.0.0

### PR DESCRIPTION
**Pull request by NobodyXu**
Also update github workflow sendfd to test all features.

Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by nagisa** [comment]
As per https://lib.rs/crates/tokio/rev, it seems like there are still a fair number of users and downloads of the 0.2 series of tokio. I wonder if it makes sense to continue supporting this… We could also ask users to “just” use an older version of `sendfd` if they rely on the older version of `tokio`, I guess.

Opionions @lovesegfault @Ekleog?

**Comment by NobodyXu** [comment]
Building tokio in the [workflow](https://github.com/NobodyXu/sendfd/runs/3608181261?check_suite_focus=true) failed, seems like the cargo version is too old.

**Comment by nagisa** [comment]
Since this change would necessitate a breaking change release, it is fine for us to bump the MSRV up to something like 1.53 in this PR as well.

**Comment by Ekleog** [comment]
I'd also think it makes sense for people who want to use older versions of tokio that they also use older versions of sendfd, so would lean towards accepting this PR :)

**Comment by nagisa** [comment]
Released 0.4.0 with these changes.

**Pull request merged**
